### ISSUE TITLE
Unable to publish pipeline from pipeline preview page

### ISSUE THREAD

**Issue by ShihChun-H** [instill-ai/instill-core#504]
While publishing a pipeline from the pipeline preview page, it is not working. On the other hand, publishing a pipeline from the pipeline builder, then it is working. Another finding is that the behavior between these two actions is different: The former does not fill in the readme and short description automatically.

[Slack Message](https://instill-ai.slack.com/archives/C0649D73KUM/p1710936674144449)

**Comment by felixcorleone** [comment]
@ShihChun-H Current pipeline builder(editor) is not allow users to publish the pipeline in pipeline "Preview" tab. Considering that the latest update for this issue was over five weeks ago, we are closing it. If there are any updates in the future, please reopen the issue and provide the latest requirements and status. Thank you.
